fascinatemtd: initial bringup for OmniRom5.1 Updates the defconfig and sets selinux to permissive
updates init - squished commit of:

use aosp recovery scripts
remove lpm and replace with healthd
update environment for omnirom
introduce bigmem support (init part)

diff --git a/usr/fascinatemtd_initramfs_files/init b/usr/fascinatemtd_initramfs_files/init
--- a/usr/fascinatemtd_initramfs_files/init
+++ b/usr/fascinatemtd_initramfs_files/init
@@ -23,45 +23,65 @@ busybox mount -t ext4 /dev/block/mmcblk0p3 /cache
 image=/stage1/ramdisk.cpio
 
 if busybox test -e /cache/.startrecovery || \
-	busybox grep -q bootmode=2 /proc/cmdline ; then
+   busybox grep -q bootmode=2 /proc/cmdline || \
+   busybox grep -q bootmode=9 /proc/cmdline; then
 	# recovery boot
+	busybox echo 'RECOVERY BOOT' >>boot.txt
 	busybox rm -fr /cache/.startrecovery
 	image=/stage1/ramdisk-recovery.cpio
+	busybox echo "loading ramdisk-recovery.cpio" >>boot.txt
 
 	# disable lpm
 	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting
+
 elif ! busybox test -e /system/build.prop ; then
+
 	# emergency boot
+	busybox echo "EMERGENCY BOOT" >>boot.txt
 	busybox umount /cache
 	make_ext4fs -b 4096 -g 32768 -i 8192 -I 256 -a /cache /dev/block/mmcblk0p3
 	busybox mount -t ext4 /dev/block/mmcblk0p3 /cache
-	busybox mkdir /cache/recovery
 
-	busybox mount -t vfat /dev/block/mmcblk1p1 /sdcard
-
-	UPDATE=$(busybox cat /sdcard/omni.cfg)
-
-	if busybox test -n "$UPDATE" ; then
-		busybox echo "install_zip(\"`echo $UPDATE`\");" > /cache/recovery/extendedcommand
+	if ! busybox test -e /cache/recovery ; then
+		busybox mkdir /cache/recovery
 	fi
 
+	busybox mount -t vfat /dev/block/mmcblk0p1 /sdcard
+	busybox sleep 1
+
+	if busybox test -e /sdcard/omni.cfg ; then
+		busybox echo "installing: `busybox cat /sdcard/omni.cfg`" >>boot.txt
+		busybox echo "creating recovery command" >>boot.txt
+		busybox touch /cache/recovery/command
+		busybox echo "--update_package=`busybox cat /sdcard/omni.cfg`" > /cache/recovery/command
+	else
+		busybox echo "omni.cfg not found" >>boot.txt
+	fi
+
+	busybox echo "loading ramdisk-recovery.cpio" >>boot.txt
 	image=/stage1/ramdisk-recovery.cpio
 
 	# disable lpm
 	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting
+
+	# umount sdcard
+	busybox umount /sdcard
+
+else
+	# android boot
+	busybox echo "ANDROID BOOT" >>boot.txt
+	busybox echo "loading ramdisk.cpio" >>boot.txt
 fi
 
 busybox umount /cache
 busybox umount /system
-busybox umount /sdcard
 busybox rmdir /sdcard
 
-busybox cpio -ui < $image
+busybox cpio -i < $image
 
-if busybox grep -q 1 /sys/class/power_supply/battery/charging_mode_booting ; then
-	# low power mode
-	busybox cp lpm.rc init.rc
-	busybox rm init.aries.rc
+if busybox grep -q mode=charger /proc/cmdline ; then
+	busybox cp /sbin/device_healthd /sbin/healthd
+	busybox chmod 775 /sbin/healthd
 fi
 
 busybox umount /sys
